title: Karhhi
description: "Mi sitio minimal con Alembic"
url: "https://karhhi.github.io"
baseurl: ""          # porque es repositorio de usuario
lang: es
timezone: America/Santiago

plugins:
  - jekyll-remote-theme

remote_theme: daviddarnes/alembic@main
